services:
  app:
    build: .
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth
    volumes:
      - auth:/var/lib/postgresql/data
volumes:
  auth:
    driver: local
